controllers:
  resource: ../src/Controller
  type: attribute

root_route_redirect:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    path: /es
    permanent: true